version: '3.8'
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
      - USER=myuser
      - PASS=mypassword
    volumes:
      - /media/data/:/downloads
      - ./config:/config
      - ./watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
