version: '3.8'
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    network_mode: host
    volumes:
      - /media/data/:/media
      - ./config:/config
      - ./cache:/cache
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
